### ISSUE TITLE
Feature Request: Ocean Villages Yes/No in config

### ISSUE THREAD

**Issue by Faedelity** [capnkirok/Voxels#13]
Similar to the config in MoVillages. It would be nice if there was a config to turn off the spawning of Creeper villages in the ocean. I don't mind them in any other biome, but having them spawn in the middle of large expanses of water removes a lot of the challenge of ocean traversal.

I am using the 1.7.10 version, and would love it if this was added to this version of the mod. (Like a lot of other heavy mod users, it will probably be a while before I start using a later version of Minecraft).

Love your mods, keep up the good work!

**Comment by capnkirok** [comment]
Good suggestion and easy to implement (my favorite kind). Thanks for the input!
