### ISSUE TITLE
NEI Tooltip issues

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/Voxels#14]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2741039-voxels-customizable-trading-with-creeper-villages?comment=105

**Comment by Faedelity** [comment]
I'm getting a similar problem but with a slightly different result; in mine, the tooltip has text, but it says all the blocks are... "undetermined", I think. Something starting with U. Using 1.7.10, massive mix of mods. Let me know if more specific information (like a log or screenshot) would be helpful.

**Comment by capnkirok** [comment]
Screenshot would be great. Thanks!

**Comment by Faedelity** [comment]
Okay, will poke at it this evening. Just posting so you know I am an not ignoring the request.

**Comment by Faedelity** [comment]
Actually, it seems that with a minimal mod loadout, I am getting exactly the same problem. I was using some NEI addons (WAILA, WAWLA, and WAILA Harvestability), and they were working as normal, but the main NEI wasn't. Here's the screenshot with the addons, so you can see how they interact with the problem. Without them, it looks just like the OP's.
![tooltip](https://cloud.githubusercontent.com/assets/6268255/19662967/ffab3bf0-99f6-11e6-9be1-cd9e3ba29ee4.png)

**Comment by capnkirok** [comment]
Thank you for the additional help here. I've got some code that becomes disabled when NEI is installed, I will see if it's affecting anything else...

**Comment by capnkirok** [comment]
Got it. Needed add an extra check for NPE for entityplayer, item, and world. 'Borrowed' code from WAWLA. Will go into next release.

![2016-11-12_09 50 10](https://cloud.githubusercontent.com/assets/9628379/20236708/abebccde-a8bd-11e6-8ef3-4e9cc504fcd6.png)
