### ISSUE TITLE
Guard sells a poisonous potato with full garbage.

### ISSUE THREAD

**Issue by KleinMarquez122** [capnkirok/Voxels#15]
I was trade the Guard Villager, but theres that sells a poison potato, but too many garbages.

**Comment by capnkirok** [comment]
Thanks for reporting the bug, KleinMarquez122, it will be fixed in the next
release.

**Comment by KleinMarquez122** [comment]
But the weapons and armors turned into poisonous potatos.

**Comment by capnkirok** [comment]
Ok, finally, I found the problem while I was upgrading to 1.10.2. Look for the fix in the 1.0.5 release.
