### ISSUE TITLE
1.10.2 Leather in farm chest shows as broken texture

### ISSUE THREAD

**Issue by FloressaX** [capnkirok/Voxels#16]
Hiya, I just installed voxels and found this little issue with the farm house/building chest.
http://imgur.com/a/ZsGJc
As you can see in jei my leather shows up fine but in the chest that generated in the voxels town it appears broken. It also appears broken in my hand.
http://imgur.com/a/ni3bX
I also disabled my texture pack for the second picture and there is no difference.
I am running quite a few mods so it may just be on my end. I just thought it was worth reporting.

**Comment by capnkirok** [comment]
Interesting and weird. What is the item? Just leather?

How does it appear with no mods installed (other than Voxels)?

PC

**Comment by FloressaX** [comment]
Okay so I removed all my mods and just played with voxels. I am running forge 2122 http://imgur.com/a/lLmic  and the issue is still there.
http://imgur.com/a/CarTS
Yes it seems to be just leather.
Edit-I just wanted to add the house/building with the animals seems to be where the leather generates in, but not always I had to find a second village on my test because no leather spawned in the first village I found.

**Comment by capnkirok** [comment]
Thank you for checking! Will get this sorted in the next update.

**Comment by capnkirok** [comment]
Ok, so there is nothing wrong with the code. It simply refers to Items.LEATHER. Must be a bug with Forge. So, I'm going to swap this out for Rabbit Stew in the short term until this is fixed. Strangely, if you turn on custom trading for the Rancher and edit the JSON file to use Leather... it works fine!

**Comment by capnkirok** [comment]
Fixed in Dev, will publish update tomorrow.
