### ISSUE TITLE
Sun rendering strangely with Voxels installed

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/Voxels#19]
Added modlist as well... suspecting optifine plus the the GuiScreen

![image](https://cloud.githubusercontent.com/assets/9628379/20320517/65ed6a96-ab72-11e6-9edb-3eceae41e6e0.png)
![image](https://cloud.githubusercontent.com/assets/9628379/20320502/5710040c-ab72-11e6-8266-8248b1bd8a6b.png)

**Comment by capnkirok** [comment]
Not able to replicate... same mods 

Any unusual settings on OptiFine? Or any shaders you have on?

![image](https://cloud.githubusercontent.com/assets/9628379/20321347/6bb0e14e-ab75-11e6-9168-52c95773c216.png)
![2016-11-15_20 51 56](https://cloud.githubusercontent.com/assets/9628379/20321368/7d41a06a-ab75-11e6-9fe1-e4f73bab529c.png)

**Comment by Frobuzmumber** [comment]
I had that same issue and found that it only occurred using the fast render with optifine.

**Comment by capnkirok** [comment]
Closing this one
