### ISSUE TITLE
Server Side Crash - Unable to start server

### ISSUE THREAD

**Issue by Frobuzmumber** [capnkirok/Voxels#2]
I first attempted to start the server with voxels and other mods, I then removed voxels and the server loaded fine. I then removed all mods and added just voxels and had the same crash issue.
Logs and crash reports are attached.

[logs.zip](https://github.com/capnkirok/Voxels/files/433927/logs.zip)

**Comment by capnkirok** [comment]
Going backwards it seems...

**Comment by capnkirok** [comment]
Yeah, server side was in bad shape. I have another version, no crashes better performance, but making a few more tweaks.
