### ISSUE TITLE
[1.10] Voxels not saving.

### ISSUE THREAD

**Issue by Kaisoul** [capnkirok/Voxels#21]
seems that my voxels are not being saved after i leave and rejoin my Lan world.

even after i tried to sell items to a creeper i received no voxels from my sales of vanilla loot.

is there any mod that would conflict with your mod to produce this problem.

**Comment by capnkirok** [comment]
Confirming, you are on 1.10? or 1.7.10? Also... you are not in Creative mode are you? Because transactions are disabled when in Creative...

**Comment by Kaisoul** [comment]
i am in 1.10    though i did bounce between creative and survival.

**Comment by capnkirok** [comment]
Can you pos your modlist just in case? Thanks!

**Comment by Kaisoul** [comment]
will do as soon as i figure out an easy method to list all my mods

**Comment by Kaisoul** [comment]
[ModList.zip](https://github.com/capnkirok/Voxels/files/595556/ModList.zip)

used the mod  ModLister to make a json file with all the mods installed then zipped it so that github would accept it.

**Comment by capnkirok** [comment]
Hey Kaisoul -

Double checking... before I start down the path of downloading all these mods :)
- Can you confirm you are receiving Voxels from your sales when in Survival mode, or is this definitely broken?
- Do all of your Voxels disappear when you log in again?
- What if you go all the way out and close Minecraft, and then go back in. Are the Voxels there, or completely gone?

**Comment by Kaisoul** [comment]
1. not sure atm will have to test that out again when i have some time gotta go make dinner for my GF and out kids atm.  
2. yes they disappear
3. still gone.

**Comment by Kaisoul** [comment]
ok i tested out voxel again...
for starters it does not save my voxel count when i log out and in.
also seems like some how i had a negative voxel count cause it took about 30-50 voxel before my screen started to show 7 voxel when i started testing.

**Comment by capnkirok** [comment]
Thanks for following up, and with all the detail. I am still working on it, don't give up hope :D

**Comment by capnkirok** [comment]
Ok, I believe this is fixed. It was a problem for all versions, not just LAN! Oops.

**Comment by JLDAGH** [comment]
Hey, running voxels 1.0.8 on Minecraft 1.10.2 on server setup. Voxels are not saving when you log out and in, seemingly identical to this issue. Mod-list here: http://www.technicpack.net/modpack/sato-one-ten-two.943441/mods

EDIT: Ok, so you aren't actually losing the voxels, but your visual display resets. It does preserve your actual number. You just can't see it.
