### ISSUE TITLE
1.10.2 Village Generation Crash

### ISSUE THREAD

**Issue by JLDAGH** [capnkirok/Voxels#28]
When a creeper village generates, the server crashes. The server restarts fine, and the village and villagers appear to have generated fine and are fully functional. It's simply the initial generation that causes the issue.

Modlist: http://www.technicpack.net/modpack/sato-one-ten-two.943441/mods

Crash log below.

[crash-2017-01-01_00.10.20-server.txt](https://github.com/capnkirok/Voxels/files/680182/crash-2017-01-01_00.10.20-server.txt)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  SHLoadingPlugin (ScalingHealth-1.10.2-1.0.2-34.jar)
  MMFMLCorePlugin (MultiMine-1.10.2.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  IvToolkit (IvToolkit-1.2.9.jar)
  SignPictureCorePlugin (SignPicture-1.10.2-2.6.1-universal.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 1/1/17 12:10 AM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at com.voxels.entities.EntityCreeperCustom.getItem(EntityCreeperCustom.java:556)
	at com.voxels.entities.EntityCreeperCustom.initCreeperChest(EntityCreeperCustom.java:513)
	at com.voxels.entities.EntityCreeperCustom.<init>(EntityCreeperCustom.java:80)
	at com.voxels.worldgen.WorldGenCreeperFountain.func_180709_b(WorldGenCreeperFountain.java:465)
	at com.voxels.worldgen.WorldGenCreeperVillage.func_180709_b(WorldGenCreeperVillage.java:523)
	at com.voxels.worldgen.WorldGenCV.generateSurface(WorldGenCV.java:104)
	at com.voxels.worldgen.WorldGenCV.generate(WorldGenCV.java:39)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.voxels.entities.EntityCreeperCustom.getItem(EntityCreeperCustom.java:556)
	at com.voxels.entities.EntityCreeperCustom.initCreeperChest(EntityCreeperCustom.java:513)
	at com.voxels.entities.EntityCreeperCustom.<init>(EntityCreeperCustom.java:80)
	at com.voxels.worldgen.WorldGenCreeperFountain.func_180709_b(WorldGenCreeperFountain.java:465)
	at com.voxels.worldgen.WorldGenCreeperVillage.func_180709_b(WorldGenCreeperVillage.java:523)
	at com.voxels.worldgen.WorldGenCV.generateSurface(WorldGenCV.java:104)
	at com.voxels.worldgen.WorldGenCV.generate(WorldGenCV.java:39)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['JLDAGH'/52894, l='world', x=-870.79, y=62.07, z=-1194.87]]
	Chunk stats: ServerChunkCache: 1108 Drop: 0
	Level seed: -3378124293421537205
	Level generator: ID 07 - RTG, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-384,82,-784), Chunk: (at 0,5,0 in -24,-49; contains blocks -384,0,-784 to -369,255,-769), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 291752 game time, 375025 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 151470 (now: false), thunder time: 2623 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3365671272 bytes (3209 MB) / 5227675648 bytes (4985 MB) up to 9544663040 bytes (9102 MB)
	JVM Flags: 3 total; -Xmx10G -Xms5G -XX:MaxPermSize=512M
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 19
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 93 mods loaded, 93 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHIJAAAA	ivtoolkit{1.2.9} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	battletowers{1.5.5} [Battle Towers] (BattleTowers-1.10.2.jar) 
	UCHIJAAAA	subcommonlib{1.1.3.0} [Subaraki's Common Library] (sublib-1.10.2-1.1.3.0.jar) 
	UCHIJAAAA	rpginventory{1.10.2 5.0.0.1} [Rpg Inventory] (rpginventory-1.10.2 v5.0.0.2.jar) 
	UCHIJAAAA	beastmaster{1.10.2 1.0.0.0} [Beastmaster Class Armor] (beastmaster-1.10.2 v1.0.0.0.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCHIJAAAA	blockarmor{2.0.1} [Block Armor] (BlockArmor-1.10.2-2.0.1.jar) 
	UCHIJAAAA	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.10.2-1.5.1.jar) 
	UCHIJAAAA	bma_addon{1.10.2 v4} [Berserker, Mage, Archer Addon for Rpg Inventory] (bma_addon-1.10.2-4.0.0.1.jar) 
	UCHIJAAAA	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAA	coroutil{1.10.2-1.1.10} [CoroUtil Library] (coroutil-1.10.2-1.1.10.jar) 
	UCHIJAAAA	extendedrenderer{v1.0} [Extended Renderer] (coroutil-1.10.2-1.1.10.jar) 
	UCHIJAAAA	configmod{v1.0} [Extended Mod Config] (coroutil-1.10.2-1.1.10.jar) 
	UCHIJAAAA	craftablehorsearmour{1.2} [Craftable Horse Armour [CHA&S]] (CraftableHorseArmor-1.3.0-1.10.jar) 
	UCHIJAAAA	cyberware{beta-0.2.6} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.6.jar) 
	UCHIJAAAA	dailies{1.10.2-6} [Bailey's Dailies] (dailies-1.10.2-6.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJAAAA	props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJAAAA	dooglamoocitiesmod{1.10.2-1.2.5} [Dooglamoo Cities] (dooglamoocitiesmod-1.10.2-1.2.5.jar) 
	UCHIJAAAA	dldungeonsjdg{1.8.13} [Doomlike Dungeons] (DoomlikeDungeons-1.8.13-MC1.10.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCHIJAAAA	eplus{4.1.0.113} [Enchanting Plus] (EnchantingPlus-1.10.2-4.1.0.115.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	sonarcore{3.1.9} [SonarCore] (SonarCore-1.10.2-3.1.9.jar) 
	UCHIJAAAA	fluxnetworks{1.0.8} [FluxNetworks] (FluxNetworks-1.10.2-1.0.8.jar) 
	UCHIJAAAA	geographicraft{0.7.5} [GeographiCraft] (GeographiCraft-1.9.4-0.7.6.jar) 
	UCHIJAAAA	grapple_hooks{1.0.8} [Grapple Hooks] (Grapple-Hooks-1.10.2-1.0.8.jar) 
	UCHIJAAAA	gyth{2.0.0.2} [Get Ya' Tanks Here] (Gyth-1.10.2-2.0.0.12.jar) 
	UCHIJAAAA	immersiveengineering{0.10-54} [Immersive Engineering] (ImmersiveEngineering-0.10-54.jar) 
	UCHIJAAAA	InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs-1.10.jar) 
	UCHIJAAAA	infinitylib{1.10.2-0.4.0} [InfinityLib] (infinitylib-0.4.0.jar) 
	UCHIJAAAA	InventoryPets{1.4.9} [Inventory Pets] (inventorypets-1.10-1.4.9.jar) 
	UCHIJAAAA	JEI{3.13.6.392} [Just Enough Items] (jei_1.10.2-3.13.6.392.jar) 
	UCHIJAAAA	ironbackpacks{1.10.2-2.2.21} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.21.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.3.3} [JourneyMap] (journeymap-1.10.2-5.3.3.jar) 
	UCHIJAAAA	levels{r4.1.3} [Levels] (Levels-1.10.2-r4.1.3.jar) 
	UCHIJAAAA	levelup{${version}} [Level Up!] (LevelUp!-0.12.5-1.10.2.jar) 
	UCHIJAAAA	lootbags{2.3.0} [Loot Bags] (LootBags-1.10.2-2.3.0.jar) 
	UCHIJAAAA	lucky_cases{1.3.3} [Lucky Cases] (LuckyCases-1.10.2-1.3.3.jar) 
	UCHIJAAAA	lycanitesmobs{1.15.1.5 - MC 1.10.2} [Lycanites Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	arcticmobs{1.15.1.5 - MC 1.10.2} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	demonmobs{1.15.1.5 - MC 1.10.2} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	desertmobs{1.15.1.5 - MC 1.10.2} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	forestmobs{1.15.1.5 - MC 1.10.2} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	freshwatermobs{1.15.1.5 - MC 1.10.2} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	infernomobs{1.15.1.5 - MC 1.10.2} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	junglemobs{1.15.1.5 - MC 1.10.2} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	mountainmobs{1.15.1.5 - MC 1.10.2} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	plainsmobs{1.15.1.5 - MC 1.10.2} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	saltwatermobs{1.15.1.5 - MC 1.10.2} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	shadowmobs{1.15.1.5 - MC 1.10.2} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	swampmobs{1.15.1.5 - MC 1.10.2} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHIJAAAA	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal.jar) 
	UCHIJAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAA	mfcombat{1.0} [Guardian Combat System] (MFCombatSystem_Guardian-1.10.2-1.0.jar) 
	UCHIJAAAA	missing_pieces{4.1.1} [Missing Pieces] (missing_pieces-1.10.2-4.1.1.jar) 
	UCHIJAAAA	AS_MultiMine{1.5.4} [Multi Mine] (MultiMine-1.10.2.jar) 
	UCHIJAAAA	naturescompass{1.3.0} [Nature's Compass] (NaturesCompass-1.10.2-1.3.0.jar) 
	UCHIJAAAA	ninjagear{1.10.2-0.4.0} [NinjaGear] (ninjagear-0.4.0.jar) 
	UCHIJAAAA	yurtmod{7.01} [Nomadic Tents] (NomadicTents[1.10.2]-7.01.jar) 
	UCHIJAAAA	omlib{1.10.2-3.0.0-37} [OMLib] (omlib-1.10.2-3.0.0-37.jar) 
	UCHIJAAAA	openmodularturrets{1.10.2-3.0.0-42} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-42.jar) 
	UCHIJAAAA	overlord{2.0.2} [Overlord] (Overlord-1.10.2-2.0.2.jar) 
	UCHIJAAAA	pandorasbox{2.1.5} [Pandora's Box] (PandorasBox-2.1.5.jar) 
	UCHIJAAAA	PersistentBits{1.0.6} [Persistent Bits] (PersistentBits-1.10.2-1.0.6.jar) 
	UCHIJAAAA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJAAAA	reccomplex{1.2.4} [Recurrent Complex] (RecurrentComplex-1.2.4.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.5.16} [Storage Drawers] (StorageDrawers-1.10.2-3.5.16.jar) 
	UCHIJAAAA	refinedstorage{1.2.14} [Refined Storage] (refinedstorage-1.2.14.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.615} [Reliquary] (Reliquary-1.10.2-1.3.3.615.jar) 
	UCHIJAAAA	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHIJAAAA	RTG{4.1.2.1} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.1.jar) 
	UCHIJAAAA	AS_Ruins{16.2} [Ruins Spawning System] (Ruins-1.10.2.jar) 
	UCHIJAAAA	SilentLib{1.1.0} [Silent Lib] (SilentLib-1.10.2-1.1.0-23.jar) 
	UCHIJAAAA	scalinghealth{1.0.2} [Scaling Health] (ScalingHealth-1.10.2-1.0.2-34.jar) 
	UCHIJAAAA	signpic{2.6.1} [SignPicture] (SignPicture-1.10.2-2.6.1-universal.jar) 
	UCHIJAAAA	valkyrielib{1.10.2-0.10.5d} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.5e.jar) 
	UCHIJAAAA	simplegenerators{1.10.2-0.10.5c} [Simple Generators] (simplegenerators-1.10.2-0.10.5c.jar) 
	UCHIJAAAA	storagedrawersextra{1.10-1.0.0} [Storage Drawers Extras] (StorageDrawersExtras-1.10.2-1.0.0.jar) 
	UCHIJAAAA	umbralux{1.10.2 v2} [Umbra - Lux Addon for Rpg Inventory] (umbralux-1.10.2-2.0.0.1.jar) 
	UCHIJAAAA	vampirism{1.0.3} [Vampirism] (Vampirism-1.10.2-1.0.3.jar) 
	UCHIJAAAA	teamlapen-lib{1.0.3} [TeamLapen Library] (Vampirism-1.10.2-1.0.3.jar) 
	UCHIJAAAA	voxels{1.0.8} [voxels] (voxels-1.10-1.0.8.jar) 
	UCHIJAAAA	waystones{2.0.10} [Waystones] (Waystones_1.10.2-2.0.10.jar) 
	UCHIJAAAA	weaponcaseloot{4.0.1} [WeaponCaseLoot] (weaponcaseloot-1.10.2-4.0.1.jar) 
	UCHIJAAAA	weather2{1.10.2-2.4.1} [Localized Weather & Storms] (weather2-1.10.2-2.4.1.jar) 
	UCHIJAAAA	wired{1.5.0} [WIRED: More Augs] (WIRED-1.5.0.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
SHLoadingPlugin (ScalingHealth-1.10.2-1.0.2-34.jar)
  net.silentchaos512.scalinghealth.asm.SHClassTransformer
MMFMLCorePlugin (MultiMine-1.10.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
IvToolkit (IvToolkit-1.2.9.jar)
  
SignPictureCorePlugin (SignPicture-1.10.2-2.6.1-universal.jar)
  com.kamesuta.mc.signpic.asm.SignPictureTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['JLDAGH'/52894, l='world', x=-870.79, y=62.07, z=-1194.87]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by capnkirok** [comment]
Thanks for the modlist, will take a look. Definitely seems like a mod conflict...

**Comment by JLDAGH** [comment]
I'm sure it is. Just not sure which one. To my untrained eye, it appears to be something to do with the Custom Creeper?

**Comment by capnkirok** [comment]
Really sorry for the very late reply. Yes, this has do to with a customized Custom Trader with an invalid JSON or modname. I've put in some error trapping, so it won't happen again. Might want to double check your JSON.

Fixed in next release.
