### ISSUE TITLE
Client side crash - While viewing standard villager trades.

### ISSUE THREAD

**Issue by Frobuzmumber** [capnkirok/Voxels#3]
While I was viewing villager trades the game crashed. I have noticed that all non vanilla minecraft or voxel mod items are showing up as 'unnamed item' (for example all tinkers items are 'unnamed item' and its the same with each and every mod's items except vanilla minecraft and voxels) and there is a major delay in the game when I hover over those items after pressing 'E'.. I have included the logs and crash report from the client (this is a single player game)

[logs8-23-16.zip](https://github.com/capnkirok/Voxels/files/433967/logs8-23-16.zip)

**Comment by Frobuzmumber** [comment]
Just had the same crash when switching to gamemode creative and then clicking on the compass to search for an item. I also noticed that NEI is not showing any items at all. It works fine when voxels is not loaded.

**Comment by capnkirok** [comment]
Hmmm... I must have broken something. Thanks for the testing !

**Comment by capnkirok** [comment]
Second bug is not a conflict with NEI, but with other mods.

Voxels tried to look up a an item price and couldn't find the price, and it tried to render null, which breaks everything. Need better error handling for the Reader.  I have your modlist, so can recreate here. Thanks!

**Comment by capnkirok** [comment]
Fixed!
