### ISSUE TITLE
Industrial Craft Items getting renamed to 'Unnamed'

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/Voxels#30]

**Comment by fkrisi11** [comment]
Hy capnkirok,

I'm Judy from the Minecraftforum.
I have additional information regarding this problem.

This is the link, where you can find the additional info (2 images, 1 text file)
In the text file, go to line 43480. This is where the error begins I think. And it carries all the way through the end of the file.
https://www.dropbox.com/sh/o007osrlg2p9t87/AACsCz6PLjrAhtcTn6RKguyla?dl=0

**Comment by fkrisi11** [comment]
Oh and what might also help is that, I am running Minecraft 1.7.10. Latest Forge.
I also added a mod list to the dropbox folder.

Also, it's not only IC items, that get named to 'Unnamed'. A lot of mod's items do this. For example: Blood Magic.

**Comment by capnkirok** [comment]
Ok, I figured this out. It actually has to do with metadata #35 . I've installed both Blood Magic and IC into the dev environment with no issues. Update coming today.
