### ISSUE TITLE
Blacklist Needed

### ISSUE THREAD

**Issue by VyxiFaye** [capnkirok/Voxels#34]
I don't see a way to make an item untradable through the system. Would be great if there was a blacklist option available in case I didn't want players to be able to buy certain vanilla items.

**Comment by capnkirok** [comment]
Yes, agree, and good idea.

**Comment by capnkirok** [comment]
Ok, I found a super simple way to do this, which just involves you setting a negative price for the item int he Prices.JSON file. No additional JSON needed. The update will come out May 1.
