### ISSUE TITLE
Extra Utilities 2 Search in world function with "T" not working when Voxels is installed

### ISSUE THREAD

**Issue by DingoX3** [capnkirok/Voxels#37]
There is a very important early to mid game function using "T" while in an inventory that Exu2 adds (used to be an NEI function) that your not able to use. It allows you to search for a similar item in nearby chests and inventories. A much needed asset when playing packs like Invasion by Darkosto that make you use multiple chests and storage till later in the game. I noticed when I press a key in my inventory (any key) the voxel amounts you see when hovering over an item dissapear. I figured this was conflicting with any key bind used while in your inventory. So i uninstalled voxels and it works fine. I looked in the configs and didn't notice anything related to it so I was hoping there could be a fix for this. Thanks.

modpack: Invasion by Darkosto v1.0.8
minecraft version: 1.10.2
voxels version: 1.10.2-1.0.8.2
forge version: 12.18.3.2316

**Comment by capnkirok** [comment]
Hey DingoX#

Yeah, type ahead search is really really really slow (like deadly slow) as the system has to recalculate the voxel values every keystroke. To fix this, I disable voxel values if you are on a search screen.

I don't know of a way to fix this other than to make it configurable... but you'd have to be super patient (like 1-2 seconds every keystroke). Will that work?

**Comment by DingoX3** [comment]
So the player would have 1-2 seconds to press T or... Not sure i understand sorry. But i do think that making it configurable would defiantly be a viable option. Can you have it list the voxels value in jei and not in the inventory? Not sure if thats possible either.

**Comment by capnkirok** [comment]
This will be closed tonight... also see #39
