### ISSUE TITLE
Most mod items are unnamed

### ISSUE THREAD

**Issue by jonasprechtl** [capnkirok/Voxels#38]
The most mod items are unnamed, so i cant search for anything in Not enought Items. While I press shift, the items get back they names.

Deutsch: Die meisten items von irgendwelchen mods ahben den namen "Unnamed" (Ohne anführungszeichen) Ich weiß nicht, wie ich das beheben kann.

**Comment by capnkirok** [comment]
This is a mod conflict.. can you tell me what mods you have in your pack?

**Comment by capnkirok** [comment]
Related to #39
