### ISSUE TITLE
Item searching very slow

### ISSUE THREAD

**Issue by jonasprechtl** [capnkirok/Voxels#39]
If i search in an ME-System, it is very laggy and takes a long time to search the correct items. I think this is because the voxels calculation. Can you add an function in the config file, to stop the mod to auto calculate voxels.

Deutsch: Wenn ich beispielsweiße in dem ME_System suche, ist das sehr langsam. Ich denke, dass es daran liegt, dass es für so viele mods die voxel menge berechnen muss. Könntest du funktion einfügen, welche das automatische voxel berechnen beendet und man dann diese Items einfach nichtmehr zum handeln verwenden kann?

**Comment by capnkirok** [comment]
Yeah, this is my recursive intelligent search causing problems when you use type-ahead. It's supposed to turn off when users are on an input screen, but it doesn't catch everything. I'm going to add a config to turn this off (you'll have to set 'Hide Voxel Values During Search' to True.)

**Comment by capnkirok** [comment]
Edit: also a problem for Kehaan on 1.7.10
