### ISSUE TITLE
Creeper Villages paths collapse if spawned over water or a hole

### ISSUE THREAD

**Issue by Frobuzmumber** [capnkirok/Voxels#4]
When the creeper villages spawn, the paths of gravel collapse and leave holes causing it almost impossible to enter some buildings and the creepers fall into them and can't get out.

![2016-08-29_17 44 26](https://cloud.githubusercontent.com/assets/9470663/18068635/5311b264-6e10-11e6-9155-12821a538f75.png)
![2016-08-29_17 44 30](https://cloud.githubusercontent.com/assets/9470663/18068637/56d519d6-6e10-11e6-862a-d2baae64bdfa.png)
![2016-08-29_17 44 40](https://cloud.githubusercontent.com/assets/9470663/18068640/5be425fc-6e10-11e6-990c-34009169e7ec.png)
![2016-08-29_17 44 50](https://cloud.githubusercontent.com/assets/9470663/18068641/5f7a1172-6e10-11e6-9146-63f7c2ea75db.png)

**Comment by capnkirok** [comment]
Thanks! Yes, that's a good find. It's because they're falling entity blocks (sand is too) which we forgot about. We'll have to make an adjustment!

**Comment by capnkirok** [comment]
Fixed
