### ISSUE TITLE
world does not load with advanced rocketry

### ISSUE THREAD

**Issue by lag42** [capnkirok/Voxels#6]
i brought this issue to the other mod, but on second though it seems more you and needs your attention see issue here:
https://github.com/zmaster587/AdvancedRocketry/issues/205

**Comment by capnkirok** [comment]
Thanks. Similar report from someone else. I need better error handling for certain item classes it appears. Checking now.

**Comment by capnkirok** [comment]
This is fixed in 1.0.2. Up now on Curse.
