### ISSUE TITLE
Curse/Forge Java Problem

### ISSUE THREAD

**Issue by BellaRose0613** [capnkirok/Voxels#7]
I was using this mod with some others, and I had the bug with the Price Checker, where it caused a crash when loading a world. I was using Curse with my private modpack and disabled Voxels. However, when I loaded it up again, it re enabled the mod, preventing me from fixing this unusual bug(I installed version 1.0.2). Also, when I tried to go into the folder and manually deleted the mod, it said I couldn't do that because Java was running apparently. The only solution was to restart my computer and delete or disable Voxels first thing. Very interesting.

**Comment by capnkirok** [comment]
Probably what happened is that Gradle Start was open in the background and was preventing restart. Only force closing or rebooting would have worked as you discovered. Nasty one.
